# Generated by Django 4.2.6 on 2023-11-24 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_user', '0002_admin_email_admin_name_alter_admin_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='admin_img',
            field=models.ImageField(null=True, upload_to='dash_css/images/adminimg/'),
        ),
    ]
