# Generated by Django 4.2.6 on 2023-11-24 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, null=True)),
                ('name', models.CharField(max_length=20, null=True)),
                ('admin_img', models.ImageField(null=True, upload_to='dash_css/images/adminimg/')),
                ('username', models.CharField(max_length=20, null=True)),
                ('password', models.CharField(max_length=30, null=True)),
            ],
        ),
    ]
