# Generated by Django 4.2.6 on 2023-11-21 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100)),
                ('agent_name', models.CharField(max_length=100)),
                ('reason', models.CharField(max_length=100)),
                ('fined_amount', models.FloatField()),
            ],
        ),
    ]
