# Generated by Django 4.2.6 on 2023-11-21 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_user', '0002_fines'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Fines',
            new_name='Fine',
        ),
    ]
