# Generated by Django 4.2.6 on 2023-11-21 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_user', '0003_rename_fines_fine'),
    ]

    operations = [
        migrations.AddField(
            model_name='fine',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Failed', 'Failed'), ('Paid', 'Paid')], max_length=100, null=True),
        ),
    ]
