# Generated by Django 4.2.6 on 2023-11-21 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_user', '0004_fine_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='fine',
            name='date_created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
