# Generated by Django 4.2.6 on 2023-11-21 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_user', '0005_fine_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fine',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
