# Generated by Django 4.2.6 on 2023-11-21 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client_user', '0006_alter_fine_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='fine',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='client_user.client'),
        ),
    ]
