# Generated by Django 4.2.6 on 2023-11-23 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_user', '0008_alter_client_address_alter_client_contact_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fine',
            old_name='client_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='fine',
            name='client',
        ),
    ]
