# Generated by Django 4.2.6 on 2023-11-23 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client_user', '0009_rename_client_name_fine_name_remove_fine_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='fine',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='client_user.client'),
        ),
    ]
