# Generated by Django 4.2.6 on 2023-11-23 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client_user', '0010_fine_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fine',
            name='name',
        ),
        migrations.AlterField(
            model_name='fine',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='client_user.client'),
        ),
    ]
