# Generated by Django 4.2.7 on 2023-11-28 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_user', '0011_remove_fine_name_alter_fine_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='dash_css/images/clientimg'),
        ),
    ]
