# Generated by Django 4.2.7 on 2023-11-28 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_user', '0013_remove_client_profile_picture_client_latitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='email',
        ),
        migrations.RemoveField(
            model_name='client',
            name='password',
        ),
    ]
