# Generated by Django 4.2.7 on 2023-11-28 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agent_user', '0005_agent_latitude_agent_longitude'),
        ('client_user', '0016_client_usertype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(default='admin', max_length=10)),
                ('notification_text', models.TextField(null=True)),
                ('agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='agent_user.agent')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='client_user.client')),
            ],
        ),
    ]
