# Generated by Django 4.2.7 on 2023-11-29 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agent_user', '0006_agentcurrentlocation'),
        ('client_user', '0018_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='fine',
            name='agent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='agent_user.agent'),
        ),
    ]
