# Generated by Django 4.2.7 on 2023-11-29 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_user', '0019_fine_agent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fine',
            name='agent_name',
        ),
    ]
