# Generated by Django 4.2.6 on 2023-11-21 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=100)),
                ('register_id', models.CharField(max_length=100)),
                ('licenses', models.ImageField(upload_to='')),
                ('agent_img', models.ImageField(upload_to='')),
                ('vehicle_img', models.ImageField(upload_to='')),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
