# Generated by Django 4.2.6 on 2023-11-24 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='agent_img',
            field=models.ImageField(upload_to='dash_css/images/agentimg/'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='licenses',
            field=models.ImageField(upload_to='dash_css/images/agentimg/'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='vehicle_img',
            field=models.ImageField(upload_to='dash_css/images/agentimg/'),
        ),
    ]
