# Generated by Django 4.2.7 on 2023-11-28 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agent_user', '0003_agent_user_agent_usertype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='email',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='password',
        ),
    ]
