# Generated by Django 4.2.7 on 2023-11-28 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_user', '0004_remove_agent_email_remove_agent_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='latitude',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='longitude',
            field=models.TextField(null=True),
        ),
    ]
